### ISSUE TITLE
An error problem 

### ISSUE THREAD

**Issue by serene66** [PatrickKueck/FASconCAT-G#2]
Hello, 
"Label not found for "next READING" at ./FASconCAT-G_v1.04.pl line 1906." 
When I get an error like this, what do I do? Thank you.

**Comment by PatrickKueck** [comment]
Hello. Thank you for writing. Seems that you have found a script-bug. I am sure that this can be fixed, but I need more info to help you. Please, send me the command line and some more info about your input data (fasta or phylip, located in the same folder or at another place than fcc-g...). BestPatrick Am 22.10.20 um 10:08 schrieb serene66
                
            
            
                
                    Von: "serene66" <notifications@github.com>Datum: 22. Oktober 2020An: "PatrickKueck/FASconCAT-G" <FASconCAT-G@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Betreff: [PatrickKueck/FASconCAT-G] An error problem  (#2)
                
                
Hello,
"Label not found for "next READING" at ./FASconCAT-G_v1.04.pl line 1906."
When I get an error like this, what do I do? Thank you.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PatrickKueck/FASconCAT-G/issues/2",
"url": "https://github.com/PatrickKueck/FASconCAT-G/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by serene66** [comment]
Hi, thank you for your reply. I found I had provided an empty file that caused the error.
