### ISSUE TITLE
Missing sequences replaced with X rather than -

### ISSUE THREAD

**Issue by ERRMoody** [PatrickKueck/FASconCAT-G#4]
Hi, is there a way to set this program to infill missing sequences with gap characters rather than X? X implies an amino acid is present but unknown (specifically not a deletion for protein data), but if the gene has been lost then X would be incorrect, as I understand it.

Thanks,
Ed

**Comment by PatrickKueck** [comment]
Hi Ed,

 

thank you for your recommendation. I implemented a new option (-g) in FCC-G, enabling you to use gap coding to fill up all your absent gene-sequence data during the concatenation process. The new version is FASconCAT-G_v1.05.pl as well as the adapted manual can be downloaded from github:

 

https://github.com/PatrickKueck/FASconCAT-G

 

I tested the new version on a smaller set of gene files. So please, let me know if you get some unexpected results, but usually the script should work as expected.

 

Best

 

Pat

 

 

----------------
Dr. Patrick Kück
Algorithmic Development
Zoological Research Museum Alexander Koenig (ZFMK)
Adenauerallee 160, 53113 Bonn, Germany
www.zfmk.de

 
 

Gesendet: Freitag, 19. März 2021 um 10:24 Uhr
Von: "Edmund R. R. Moody" ***@***.***>
An: "PatrickKueck/FASconCAT-G" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [PatrickKueck/FASconCAT-G] Missing sequences replaced with X rather than - (#4)


 

Hi, is there a way to set this program to infill missing sequences with gap characters rather than X? X implies an amino acid is present but missing, but if the gene has been lost then it's incorrect, as I understand it.

Thanks,
Ed

**Comment by ERRMoody** [comment]
Great, thanks!
